name = "TurbulentWords"
uuid = "61083c21-b130-4e74-9cd1-836f8dfec7b9"
authors = ["Navid C. Constantinou <navidcy@users.noreply.github.com> and Gregory L. Wagner <glwagner@users.noreply.github.com>"]
version = "0.1.0"

[deps]
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
Makie = "ee78f7c6-11fb-53f2-987a-cfe4a2b5a57a"
Oceananigans = "9e8cae18-63c1-5223-a75c-80ca9d6e9a09"

[compat]
Makie = "0.19"
Oceananigans = "0.90"
